replicaCount: 1

image:
  repository: hapiproject/hapi
  tag: v8.2.0-1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

extraEnv:
  - name: "HAPI_FHIR_ALLOW_EXTERNAL_REFERENCES"
    value: "true"
  - name: "HAPI_FHIR_REUSE_CACHED_SEARCH_RESULTS_MILLIS"
    value: "60000"
  - name: "HAPI_FHIR_SERVER_ADDRESS"
    value: "http://0.0.0.0:8080/fhir"
